# Generated by Django 5.1.3

from django.db import migrations
from django.utils import timezone
from decimal import Decimal

LANDLORD_PLANS = [
    {
        "name": "Solo",
        "slug": "solo",
        "plan_type": "landlord",
        "monthly_price": "1500.00",
        "annual_price": "15300.00",
        "max_units": 10,
        "max_properties": 2,
        "sms_quota": 50,
        "features": {
            # ── Payments ──────────────────────────────
            "mpesa_collection": True,
            "bank_collection": True,
            "automated_receipts": True,
            "partial_payments": True,
            "penalty_rules": True,
            "penalty_per_unit_override": False,

            # ── Debt Recovery ─────────────────────────
            "debt_recovery_full": True,             # full 7-stage
            "demand_letter_generation": True,
            "quit_notice_generation": True,

            # ── Documents ─────────────────────────────
            "lease_generation": True,
            "inspection_reports": True,
            "document_storage": True,
            "document_version_history": False,
            "document_bulk_download": False,
            "white_label_receipts": False,

            # ── Maintenance ───────────────────────────
            "maintenance_tickets": True,

            # ── Reminders ─────────────────────────────
            "email_reminders": True,
            "sms_reminders": False,
            "lease_renewal_reminders": True,

            # ── Listings ──────────────────────────────
            "auto_listing": True,
            "listing_analytics_basic": True,
            "listing_analytics_full": False,
            "viewing_scheduler": True,
            "featured_listing_addon": True,

            # ── Utilities ─────────────────────────────
            "utility_tracking_manual": True,
            "utility_billing_automated": False,

            # ── Reports ───────────────────────────────
            "report_collection": True,
            "report_occupancy": True,
            "report_maintenance_cost": False,
            "report_profit_loss": False,
            "report_pdf_export": False,
            "report_excel_export": False,
            "report_scheduled_delivery": False,

            # ── Communication ─────────────────────────
            "in_app_messaging": True,
            "bulk_sms": False,
            "tenant_payment_history_view": True,

            # ── Properties / Scale ────────────────────
            "property_manager_delegation": False,
            "pm_permission_config": False,
            "commission_tracking": False,

            # ── Support ───────────────────────────────
            "support_email": True,
            "support_priority_email": False,
            "support_phone": False,

            # ── API ───────────────────────────────────
            "api_access": False,
        }
    },
    {
        "name": "Starter",
        "slug": "starter",
        "plan_type": "landlord",
        "monthly_price": "2500.00",
        "annual_price": "25500.00",
        "max_units": 30,
        "max_properties": 5,
        "sms_quota": 200,
        "features": {
            "mpesa_collection": True,
            "bank_collection": True,
            "automated_receipts": True,
            "partial_payments": True,
            "penalty_rules": True,
            "penalty_per_unit_override": False,

            "debt_recovery_full": True,
            "demand_letter_generation": True,
            "quit_notice_generation": True,

            "lease_generation": True,
            "inspection_reports": True,
            "document_storage": True,
            "document_version_history": False,
            "document_bulk_download": False,
            "white_label_receipts": False,

            "maintenance_tickets": True,

            "email_reminders": True,
            "sms_reminders": True,
            "lease_renewal_reminders": True,

            "auto_listing": True,
            "listing_analytics_basic": True,
            "listing_analytics_full": False,
            "viewing_scheduler": True,
            "featured_listing_addon": True,

            "utility_tracking_manual": True,
            "utility_billing_automated": False,

            "report_collection": True,
            "report_occupancy": True,
            "report_maintenance_cost": True,
            "report_profit_loss": True,
            "report_pdf_export": True,
            "report_excel_export": False,
            "report_scheduled_delivery": False,

            "in_app_messaging": True,
            "bulk_sms": True,
            "tenant_payment_history_view": True,

            "property_manager_delegation": False,
            "pm_permission_config": False,
            "commission_tracking": False,

            "support_email": True,
            "support_priority_email": True,
            "support_phone": False,

            "api_access": False,
        }
    },
    {
        "name": "Growth",
        "slug": "growth",
        "plan_type": "landlord",
        "monthly_price": "6000.00",
        "annual_price": "61200.00",
        "max_units": 75,
        "max_properties": -1,
        "sms_quota": 500,
        "features": {
            "mpesa_collection": True,
            "bank_collection": True,
            "automated_receipts": True,
            "partial_payments": True,
            "penalty_rules": True,
            "penalty_per_unit_override": True,

            "debt_recovery_full": True,
            "demand_letter_generation": True,
            "quit_notice_generation": True,

            "lease_generation": True,
            "inspection_reports": True,
            "document_storage": True,
            "document_version_history": True,
            "document_bulk_download": True,
            "white_label_receipts": True,

            "maintenance_tickets": True,

            "email_reminders": True,
            "sms_reminders": True,
            "lease_renewal_reminders": True,

            "auto_listing": True,
            "listing_analytics_basic": True,
            "listing_analytics_full": True,
            "viewing_scheduler": True,
            "featured_listing_addon": True,

            "utility_tracking_manual": True,
            "utility_billing_automated": True,

            "report_collection": True,
            "report_occupancy": True,
            "report_maintenance_cost": True,
            "report_profit_loss": True,
            "report_pdf_export": True,
            "report_excel_export": True,
            "report_scheduled_delivery": True,

            "in_app_messaging": True,
            "bulk_sms": True,
            "tenant_payment_history_view": True,

            "property_manager_delegation": True,
            "pm_permission_config": True,
            "commission_tracking": True,

            "support_email": True,
            "support_priority_email": True,
            "support_phone": False,

            "api_access": False,
        }
    },
    {
        "name": "Professional",
        "slug": "professional",
        "plan_type": "landlord",
        "monthly_price": "10000.00",
        "annual_price": "102000.00",
        "max_units": 150,
        "max_properties": -1,
        "sms_quota": 1000,
        "features": {
            "mpesa_collection": True,
            "bank_collection": True,
            "automated_receipts": True,
            "partial_payments": True,
            "penalty_rules": True,
            "penalty_per_unit_override": True,
            "debt_recovery_full": True,
            "demand_letter_generation": True,
            "quit_notice_generation": True,
            "lease_generation": True,
            "inspection_reports": True,
            "document_storage": True,
            "document_version_history": True,
            "document_bulk_download": True,
            "white_label_receipts": True,
            "maintenance_tickets": True,
            "email_reminders": True,
            "sms_reminders": True,
            "lease_renewal_reminders": True,
            "auto_listing": True,
            "listing_analytics_basic": True,
            "listing_analytics_full": True,
            "viewing_scheduler": True,
            "featured_listing_addon": True,
            "utility_tracking_manual": True,
            "utility_billing_automated": True,
            "report_collection": True,
            "report_occupancy": True,
            "report_maintenance_cost": True,
            "report_profit_loss": True,
            "report_pdf_export": True,
            "report_excel_export": True,
            "report_scheduled_delivery": True,
            "in_app_messaging": True,
            "bulk_sms": True,
            "tenant_payment_history_view": True,
            "property_manager_delegation": True,
            "pm_permission_config": True,
            "commission_tracking": True,

            "advanced_analytics": True,
            "custom_report_builder": True,
            "dedicated_account_manager": True,
            "support_email": True,
            "support_priority_email": True,
            "support_phone": True,

            "api_access": False,
        }
    },
    {
        "name": "Enterprise",
        "slug": "enterprise",
        "plan_type": "landlord",
        "monthly_price": "0.00",
        "annual_price": "0.00",
        "max_units": -1,
        "max_properties": -1,
        "sms_quota": -1,
        "features": {
            "mpesa_collection": True,
            "bank_collection": True,
            "automated_receipts": True,
            "partial_payments": True,
            "penalty_rules": True,
            "penalty_per_unit_override": True,
            "debt_recovery_full": True,
            "demand_letter_generation": True,
            "quit_notice_generation": True,
            "lease_generation": True,
            "inspection_reports": True,
            "document_storage": True,
            "document_version_history": True,
            "document_bulk_download": True,
            "white_label_receipts": True,
            "maintenance_tickets": True,
            "email_reminders": True,
            "sms_reminders": True,
            "lease_renewal_reminders": True,
            "auto_listing": True,
            "listing_analytics_basic": True,
            "listing_analytics_full": True,
            "viewing_scheduler": True,
            "featured_listing_addon": True,
            "utility_tracking_manual": True,
            "utility_billing_automated": True,
            "report_collection": True,
            "report_occupancy": True,
            "report_maintenance_cost": True,
            "report_profit_loss": True,
            "report_pdf_export": True,
            "report_excel_export": True,
            "report_scheduled_delivery": True,
            "in_app_messaging": True,
            "bulk_sms": True,
            "tenant_payment_history_view": True,
            "property_manager_delegation": True,
            "pm_permission_config": True,
            "commission_tracking": True,
            "advanced_analytics": True,
            "custom_report_builder": True,
            "dedicated_account_manager": True,
            "support_email": True,
            "support_priority_email": True,
            "support_phone": True,
            "api_access": True,
            "white_label": True,
            "custom_integrations": True,
            "sla_guarantee": True,
        }
    },
]

PM_PLANS = [
    {
        "name": "Starter PM",
        "slug": "starter_pm",
        "plan_type": "property_manager",
        "monthly_price": "3000.00",
        "annual_price": "30600.00",
        "max_units": 50,
        "max_properties": -1,
        "sms_quota": 300,
        "features": {
            "manage_multiple_landlords": True,
            "commission_tracking": True,
            "monthly_commission_reports": True,
            "task_management": True,
            "debt_recovery_workflow": True,
            "full_document_generation": True,
            "advanced_analytics": False,
            "bulk_operations": False,
            "pm_profile_directory": False,
            "api_access": False,
            "white_label": False,
        }
    },
    {
        "name": "Professional PM",
        "slug": "professional_pm",
        "plan_type": "property_manager",
        "monthly_price": "6000.00",
        "annual_price": "61200.00",
        "max_units": 150,
        "max_properties": -1,
        "sms_quota": 1000,
        "features": {
            "manage_multiple_landlords": True,
            "commission_tracking": True,
            "monthly_commission_reports": True,
            "task_management": True,
            "debt_recovery_workflow": True,
            "full_document_generation": True,
            "advanced_analytics": True,
            "bulk_operations": True,
            "pm_profile_directory": True,
            "api_access": False,
            "white_label": False,
        }
    },
    {
        "name": "Enterprise PM",
        "slug": "enterprise_pm",
        "plan_type": "property_manager",
        "monthly_price": "0.00",
        "annual_price": "0.00",
        "max_units": -1,
        "max_properties": -1,
        "sms_quota": -1,
        "features": {
            "manage_multiple_landlords": True,
            "commission_tracking": True,
            "monthly_commission_reports": True,
            "task_management": True,
            "debt_recovery_workflow": True,
            "full_document_generation": True,
            "advanced_analytics": True,
            "bulk_operations": True,
            "pm_profile_directory": True,
            "api_access": True,
            "white_label": True,
        }
    },
]

def seed_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('subscriptions', 'SubscriptionPlan')
    
    # Iterate through all plans, saving them to DB
    all_plans = LANDLORD_PLANS + PM_PLANS
    for plan_data in all_plans:
        # Decimals handle conversion
        plan_data['monthly_price'] = Decimal(plan_data['monthly_price'])
        plan_data['annual_price'] = Decimal(plan_data['annual_price'])
        
        SubscriptionPlan.objects.update_or_create(
            slug=plan_data['slug'],
            defaults=plan_data
        )

def unseed_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('subscriptions', 'SubscriptionPlan')
    
    all_slugs = [p['slug'] for p in LANDLORD_PLANS] + [p['slug'] for p in PM_PLANS]
    SubscriptionPlan.objects.filter(slug__in=all_slugs).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_plans, unseed_plans),
    ]
