# Generated by Django 6.0.3 on 2026-03-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_extensions_indexes_audit_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, help_text='National ID number. Collected at registration, stored here.', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when user accepted T&C. Required by KDPA 2019.', null=True),
        ),
    ]
