# Generated by Django 6.0.3 on 2026-03-11 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('equity', 'Equity Bank'), ('kcb', 'KCB Bank'), ('cooperative', 'Co-operative Bank'), ('absa', 'Absa Bank Kenya'), ('stanchart', 'Standard Chartered'), ('ncba', 'NCBA Bank'), ('family', 'Family Bank'), ('im_bank', 'I&M Bank'), ('dtb', 'Diamond Trust Bank'), ('sidian', 'Sidian Bank'), ('other', 'Other')], max_length=50)),
                ('account_name', models.CharField(help_text='Name as registered with the bank — used for payment verification.', max_length=200)),
                ('account_number', models.CharField(max_length=30)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'db_table': 'bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='MpesaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('till', 'Till Number'), ('paybill', 'Paybill Number')], default='till', max_length=10)),
                ('till_number', models.CharField(blank=True, max_length=10)),
                ('paybill_number', models.CharField(blank=True, max_length=10)),
                ('account_number', models.CharField(blank=True, help_text='Reference number tenants enter when paying via paybill.', max_length=50)),
                ('account_name', models.CharField(blank=True, help_text='Friendly label shown in UI, e.g. "Equity Bank Paybill".', max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False, help_text='Set True after first successful payment received.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'M-Pesa Account',
                'verbose_name_plural': 'M-Pesa Accounts',
                'db_table': 'mpesa_accounts',
            },
        ),
    ]
