# Generated by Django 6.0.3 on 2026-03-11 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landlords', '0001_initial'),
        ('properties', '0003_remove_property_pm_property_pm_can_add_tenants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, help_text='National ID number. Required before admin approval.', max_length=20)),
                ('company_name', models.CharField(blank=True, help_text='Optional company or agency name.', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Short bio shown to landlords when they search for PMs.')),
                ('is_searchable', models.BooleanField(default=False, help_text='Controls PM visibility in landlord search. True when onboarding complete.')),
                ('id_copy_front_url', models.URLField(blank=True)),
                ('id_copy_back_url', models.URLField(blank=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Default commission % (e.g. 10.00 = 10%). Negotiated per property.', max_digits=5)),
                ('subscription_tier', models.CharField(choices=[('starter_pm', 'Starter PM — up to 50 units, Ksh 3,000/mo'), ('professional_pm', 'Professional PM — up to 150 units, Ksh 6,000/mo'), ('enterprise_pm', 'Enterprise PM — custom pricing')], default='starter_pm', max_length=20)),
                ('subscription_active', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Required if approval_status=rejected.')),
                ('onboarding_step_profile_completed', models.BooleanField(default=False)),
                ('onboarding_step_subscription_completed', models.BooleanField(default=False)),
                ('onboarding_step_banking_completed', models.BooleanField(default=False)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin user who approved or rejected this PM.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_approvals', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pm_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Manager',
                'verbose_name_plural': 'Property Managers',
                'db_table': 'property_managers',
            },
        ),
        migrations.CreateModel(
            name='PmAssignmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Agreed commission rate for this property (%).', max_digits=5)),
                ('can_add_tenants', models.BooleanField(default=True)),
                ('can_handle_maintenance', models.BooleanField(default=True)),
                ('expense_approval_threshold', models.DecimalField(decimal_places=2, default=10000, help_text='PM must get landlord approval for expenses above this amount.', max_digits=10)),
                ('proposed_start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending — awaiting PM response'), ('accepted', 'Accepted — PM managing property'), ('declined', 'Declined — PM said no'), ('cancelled', 'Cancelled — landlord withdrew request'), ('expired', 'Expired — PM did not respond in time')], db_index=True, default='pending', max_length=15)),
                ('decline_reason', models.TextField(blank=True, help_text='Reason provided by PM when declining.')),
                ('invite_email', models.EmailField(blank=True, max_length=254)),
                ('invite_name', models.CharField(blank=True, max_length=200)),
                ('invite_phone', models.CharField(blank=True, max_length=15)),
                ('invite_token', models.CharField(blank=True, db_index=True, help_text='Secure random token. Blank for existing-PM assignments.', max_length=64)),
                ('invite_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_assignment_requests', to='landlords.landlord')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_assignment_requests', to='properties.property')),
                ('pm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_requests', to='property_managers.propertymanager')),
            ],
            options={
                'verbose_name': 'PM Assignment Request',
                'verbose_name_plural': 'PM Assignment Requests',
                'db_table': 'pm_assignment_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField(blank=True, help_text='FK to payments.Payment. Stub until apps/payments/ is built.', null=True)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period', models.CharField(help_text='YYYY-MM format — which month this commission is for.', max_length=7)),
                ('status', models.CharField(choices=[('pending', 'Pending — rent collected, commission not yet paid'), ('paid', 'Paid — landlord has transferred commission to PM'), ('disputed', 'Disputed — under review'), ('waived', 'Waived — landlord waived this commission')], db_index=True, default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_records', to='properties.property')),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_records', to='property_managers.propertymanager')),
            ],
            options={
                'verbose_name': 'Commission Record',
                'verbose_name_plural': 'Commission Records',
                'db_table': 'commission_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PmServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(choices=[('nairobi', 'Nairobi City'), ('mombasa', 'Mombasa'), ('kwale', 'Kwale'), ('kilifi', 'Kilifi'), ('tana_river', 'Tana River'), ('lamu', 'Lamu'), ('taita_taveta', 'Taita-Taveta'), ('garissa', 'Garissa'), ('wajir', 'Wajir'), ('mandera', 'Mandera'), ('marsabit', 'Marsabit'), ('isiolo', 'Isiolo'), ('meru', 'Meru'), ('tharaka_nithi', 'Tharaka-Nithi'), ('embu', 'Embu'), ('kitui', 'Kitui'), ('machakos', 'Machakos'), ('makueni', 'Makueni'), ('nyandarua', 'Nyandarua'), ('nyeri', 'Nyeri'), ('kirinyaga', 'Kirinyaga'), ('muranga', "Murang'a"), ('kiambu', 'Kiambu'), ('turkana', 'Turkana'), ('west_pokot', 'West Pokot'), ('samburu', 'Samburu'), ('trans_nzoia', 'Trans-Nzoia'), ('uasin_gishu', 'Uasin Gishu'), ('elgeyo_marakwet', 'Elgeyo-Marakwet'), ('nandi', 'Nandi'), ('baringo', 'Baringo'), ('laikipia', 'Laikipia'), ('nakuru', 'Nakuru'), ('narok', 'Narok'), ('kajiado', 'Kajiado'), ('kericho', 'Kericho'), ('bomet', 'Bomet'), ('kakamega', 'Kakamega'), ('vihiga', 'Vihiga'), ('bungoma', 'Bungoma'), ('busia', 'Busia'), ('siaya', 'Siaya'), ('kisumu', 'Kisumu'), ('homa_bay', 'Homa Bay'), ('migori', 'Migori'), ('kisii', 'Kisii'), ('nyamira', 'Nyamira')], help_text='One of the 47 Kenyan counties.', max_length=50)),
                ('area', models.CharField(blank=True, help_text='Specific area within the county. Blank = entire county.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='property_managers.propertymanager')),
            ],
            options={
                'verbose_name': 'PM Service Area',
                'verbose_name_plural': 'PM Service Areas',
                'db_table': 'pm_service_areas',
                'ordering': ['county', 'area'],
                'unique_together': {('pm', 'county', 'area')},
            },
        ),
    ]
