# Generated by Django 6.0.3 on 2026-03-11 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_db_views'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_start', models.DateField()),
                ('lease_end', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rent_due_day', models.IntegerField(default=1)),
                ('grace_period_days', models.IntegerField(default=3, help_text='Days after rent_due_day before late penalty kicks in.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired — end date passed, not renewed'), ('terminated', 'Terminated — ended early by mutual agreement'), ('pending', 'Pending — signed but not yet started')], db_index=True, default='active', max_length=15)),
                ('tenant_signed_at', models.DateTimeField(blank=True, null=True)),
                ('lease_document_url', models.URLField(blank=True, help_text='Cloudinary URL of the generated lease PDF. Set by apps/documents/.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_lease', models.ForeignKey(blank=True, help_text='The lease this one replaced (for renewals).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='leases.lease')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='tenants.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='properties.unit')),
            ],
            options={
                'verbose_name': 'Lease',
                'verbose_name_plural': 'Leases',
                'db_table': 'leases',
                'ordering': ['-lease_start'],
            },
        ),
    ]
