# Generated by Django 6.0.3 on 2026-03-11 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, help_text='National ID number. Collected at registration, stored here.', max_length=20)),
                ('estimated_units_range', models.CharField(blank=True, choices=[('1-10', '1 to 10 units'), ('11-30', '11 to 30 units'), ('31-75', '31 to 75 units'), ('76-150', '76 to 150 units'), ('150+', 'More than 150 units')], help_text='Stored permanently for analytics + used to pre-select subscription tier.', max_length=10)),
                ('avatar_url', models.URLField(blank=True)),
                ('id_copy_front_url', models.URLField(blank=True, help_text='Front of National ID — Cloudinary URL.')),
                ('id_copy_back_url', models.URLField(blank=True, help_text='Back of National ID — Cloudinary URL.')),
                ('subscription_tier', models.CharField(blank=True, choices=[('solo', 'Solo — Ksh 1,500/mo'), ('starter', 'Starter — Ksh 2,500/mo'), ('growth', 'Growth — Ksh 6,000/mo'), ('professional', 'Professional — Ksh 10,000/mo'), ('enterprise', 'Enterprise — Custom')], max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('terms_accepted_at', models.DateTimeField(blank=True, help_text='Timestamp when landlord accepted T&C. Required by KDPA 2019.', null=True)),
                ('onboarding_step_profile_completed', models.BooleanField(default=False)),
                ('onboarding_step_mpesa_completed', models.BooleanField(default=False)),
                ('onboarding_step_property_completed', models.BooleanField(default=False)),
                ('onboarding_step_units_completed', models.BooleanField(default=False)),
                ('onboarding_step_tenants_completed', models.BooleanField(default=False)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete. Set when landlord account is suspended.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landlords_approved', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Landlord',
                'verbose_name_plural': 'Landlords',
                'db_table': 'landlords',
            },
        ),
    ]
