# Generated by Django 6.0.3 on 2026-03-11 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landlords', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_mode', models.CharField(choices=[('self_managed', 'Self Managed'), ('delegated', 'Delegated to PM')], default='self_managed', max_length=20)),
                ('pm_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('flat', 'Flat / Apartment'), ('house', 'House / Bungalow'), ('bedsitter', 'Bedsitter'), ('office', 'Office Space'), ('plot', 'Plot / Land'), ('commercial', 'Commercial Space'), ('other', 'Other')], max_length=20)),
                ('listing_type', models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale'), ('both', 'Rent & Sale')], default='rent', max_length=10)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('county', models.CharField(choices=[('nairobi', 'Nairobi City'), ('mombasa', 'Mombasa'), ('kwale', 'Kwale'), ('kilifi', 'Kilifi'), ('tana_river', 'Tana River'), ('lamu', 'Lamu'), ('taita_taveta', 'Taita-Taveta'), ('garissa', 'Garissa'), ('wajir', 'Wajir'), ('mandera', 'Mandera'), ('marsabit', 'Marsabit'), ('isiolo', 'Isiolo'), ('meru', 'Meru'), ('tharaka_nithi', 'Tharaka-Nithi'), ('embu', 'Embu'), ('kitui', 'Kitui'), ('machakos', 'Machakos'), ('makueni', 'Makueni'), ('nyandarua', 'Nyandarua'), ('nyeri', 'Nyeri'), ('kirinyaga', 'Kirinyaga'), ('muranga', "Murang'a"), ('kiambu', 'Kiambu'), ('turkana', 'Turkana'), ('west_pokot', 'West Pokot'), ('samburu', 'Samburu'), ('trans_nzoia', 'Trans-Nzoia'), ('uasin_gishu', 'Uasin Gishu'), ('elgeyo_marakwet', 'Elgeyo-Marakwet'), ('nandi', 'Nandi'), ('baringo', 'Baringo'), ('laikipia', 'Laikipia'), ('nakuru', 'Nakuru'), ('narok', 'Narok'), ('kajiado', 'Kajiado'), ('kericho', 'Kericho'), ('bomet', 'Bomet'), ('kakamega', 'Kakamega'), ('vihiga', 'Vihiga'), ('bungoma', 'Bungoma'), ('busia', 'Busia'), ('siaya', 'Siaya'), ('kisumu', 'Kisumu'), ('homa_bay', 'Homa Bay'), ('migori', 'Migori'), ('kisii', 'Kisii'), ('nyamira', 'Nyamira')], max_length=30)),
                ('area', models.CharField(max_length=100)),
                ('estate', models.CharField(blank=True, max_length=100)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('declared_units', models.IntegerField(default=1)),
                ('actual_units', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='landlords.landlord')),
                ('pm', models.ForeignKey(blank=True, help_text='Set by property_managers app when landlord delegates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(help_text='e.g. A1, 101, Ground Floor Left', max_length=20)),
                ('bedrooms', models.IntegerField(default=0, help_text='0 = bedsitter/studio')),
                ('bathrooms', models.IntegerField(default=1)),
                ('size_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('floor_level', models.IntegerField(blank=True, help_text='Ground=0, 1st=1 etc.', null=True)),
                ('furnished', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('rent_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance')], default='vacant', max_length=15)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'db_table': 'units',
                'unique_together': {('property', 'unit_number')},
            },
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudinary_id', models.CharField(blank=True, max_length=255)),
                ('photo_url', models.URLField()),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.property')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='properties.unit')),
            ],
            options={
                'verbose_name': 'Property Photo',
                'db_table': 'property_photos',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PenaltyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_type', models.CharField(choices=[('percentage', 'Percentage of rent'), ('fixed', 'Fixed amount (Ksh)')], max_length=15)),
                ('penalty_value', models.DecimalField(decimal_places=2, help_text='If percentage: value is 5.00 = 5%. If fixed: value is Ksh amount.', max_digits=8)),
                ('grace_period_days', models.IntegerField(default=3, help_text='Days after rent due date before penalty applies.')),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalty_rules', to='properties.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalty_rules', to='properties.unit')),
            ],
            options={
                'verbose_name': 'Penalty Rule',
                'db_table': 'penalty_rules',
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_name', models.CharField(choices=[('swimming_pool', 'Swimming Pool'), ('gym', 'Gym'), ('backup_generator', 'Backup Generator'), ('24hr_security', '24-Hour Security'), ('cctv', 'CCTV'), ('parking', 'Parking'), ('elevator', 'Elevator / Lift'), ('wifi', 'Internet / Wi-Fi'), ('playground', 'Playground'), ('pet_friendly', 'Pet Friendly')], max_length=30)),
                ('available', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Amenity',
                'db_table': 'property_amenities',
                'unique_together': {('property', 'amenity_name')},
            },
        ),
        migrations.RunSQL(
            sql='''
            ALTER TABLE penalty_rules
            ADD CONSTRAINT chk_penalty_rule_target
            CHECK (
                (property_id IS NOT NULL AND unit_id IS NULL)
                OR
                (unit_id IS NOT NULL AND property_id IS NULL)
            );
            ''',
            reverse_sql='''
            ALTER TABLE penalty_rules DROP CONSTRAINT chk_penalty_rule_target;
            ''',
        ),
    ]
