# Generated by Django 6.0.3 on 2026-03-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_db_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='pm',
        ),
        migrations.AddField(
            model_name='property',
            name='pm_can_add_tenants',
            field=models.BooleanField(default=True, help_text='Whether the PM is allowed to add tenants to this property.'),
        ),
        migrations.AddField(
            model_name='property',
            name='pm_can_handle_maintenance',
            field=models.BooleanField(default=True, help_text='Whether the PM can handle maintenance requests.'),
        ),
        migrations.AddField(
            model_name='property',
            name='pm_commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission % for this property. Set on assignment acceptance.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='pm_expense_approval_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='PM must get landlord approval for expenses above this amount.', max_digits=10, null=True),
        ),
    ]
