# Generated by Django 6.0.3 on 2026-03-11 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_property_pm_property_pm_can_add_tenants_and_more'),
        ('property_managers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_manager',
            field=models.ForeignKey(blank=True, help_text='Set by property_managers app when landlord delegates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_properties', to='property_managers.propertymanager'),
        ),
    ]
