# Generated by Django 6.0.3 on 2026-03-11 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, help_text='National ID number.', max_length=20)),
                ('phone_alt', models.CharField(blank=True, help_text='Alternative contact number.', max_length=15)),
                ('id_copy_front_url', models.URLField(blank=True)),
                ('id_copy_back_url', models.URLField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100)),
                ('employer_name', models.CharField(blank=True, max_length=200)),
                ('employer_contact', models.CharField(blank=True, max_length=100)),
                ('payment_preference', models.CharField(choices=[('mpesa', 'M-Pesa STK Push'), ('bank', 'Bank Transfer')], default='mpesa', max_length=10)),
                ('notification_preference', models.CharField(choices=[('sms', 'SMS Only'), ('email', 'Email Only'), ('sms_email', 'SMS and Email')], default='sms', help_text='How the tenant prefers to receive reminders.', max_length=10)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('has_changed_password', models.BooleanField(default=False)),
                ('has_viewed_lease', models.BooleanField(default=False)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants',
            },
        ),
    ]
